// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Precificador.Infrastructure.Persistence;

#nullable disable

namespace Precificador.Infrastructure.Migrations
{
    [DbContext(typeof(PrecificadorDbContext))]
    partial class PrecificadorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Precificador.Core.Insumos.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadeBase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.ToTable("Insumos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
